### ISSUE TITLE
Enhancement: show mod images (like on thunderstore)

### ISSUE THREAD

**Issue by laundmo** [scottbot95/RoR2ModManager#41] opened 2019-05-02 17:08 UTC
basic idea: show the mod logo image in the mod manager

ive made a screenshot with the areas where it would be nice to have the logo:

![](https://i.imgur.com/9eMAj1u.png)

**Comment by scottbot95** [comment] 2019-05-02 19:10
I want to do something like this, as well as including the readme, but the problem is without trying to parse the thunderstore's HTML for the image links, the app would have to download all the package zips to get the icons.

I might end up scraping the data from thunderstore's website though

**Comment by scottbot95** [comment] 2019-05-02 23:13
Actually I'm dumb the thunderstore api totally provides an icon url. I'll include this in the next release

**Comment by laundmo** [comment] 2019-05-02 23:24
well i would have offered to write a quick parser for you but that last comment solves it :)

**Comment by scottbot95** [comment] 2019-05-03 00:20
Just merged PR #47 which adds package icons. I'll be making a new release later today with that and several other new features.

**Closed by scottbot95** 2019-05-03 00:20 UTC
Labels: enhancement
