### ISSUE TITLE
apply button doesnt do anything

### ISSUE THREAD

**Issue by laundmo** [scottbot95/RoR2ModManager#56] opened 2019-05-03 15:13 UTC
i wanted to share my mod setup with a friend, so i sent him my exported json and he tried to import it. in the import window though the 'apply' button doesnt do anything. he clicked it and nothing happened. 

later we found out that the apply button never did anything.

he did not have bepinex installed at the time

**Comment by scottbot95** [comment] 2019-05-03 19:38
Interesting. You should be able to `ctrl+shift+i` from the import dialog to open the dev console ( if that doesn't work hit alt to show the menu then. Then you can hit `view` -> `Toggle Developer Tools).

If you could post the json and any errors from the console, I'm sure that would be helpful.

**Comment by scottbot95** [comment] 2019-05-03 20:21
Also I'd be interested to know whether or not it prints a line like `Loaded valid profile /* {...} */`

**Comment by dmratcliffe** [comment] 2019-05-08 22:42
@scottbot95 I has a similar issue, it appears it doesn't have permissions for the temp directory

`main.2960c0c8a344bf598335.js:1 ERROR Error: Uncaught (in promise): Error: EPERM: operation not permitted, mkdir 'C:\Program Files\RoR2ModManager\BepInEx'
Error: EPERM: operation not permitted, mkdir 'C:\Program Files\RoR2ModManager\BepInEx'
    at P (polyfills.441ef106c9a103287018.js:1)
    at polyfills.441ef106c9a103287018.js:1
    at s (main.2960c0c8a344bf598335.js:1)
    at e.invoke (polyfills.441ef106c9a103287018.js:1)
    at Object.onInvoke (main.2960c0c8a344bf598335.js:1)
    at e.invoke (polyfills.441ef106c9a103287018.js:1)
    at t.run (polyfills.441ef106c9a103287018.js:1)
    at polyfills.441ef106c9a103287018.js:1
    at e.invokeTask (polyfills.441ef106c9a103287018.js:1)
    at Object.onInvokeTask (main.2960c0c8a344bf598335.js:1)`

**Comment by scottbot95** [comment] 2019-05-08 22:46
Interesting, it looks like it's trying to install BepInEx into the modmanagers folder. Not sure why it's doing that. Do you have your RoR2 install directory set properly?

**Comment by dmratcliffe** [comment] 2019-05-08 22:48
@scottbot95 Ah, apparently the first start doesn't set the directory correctly. I changed it proper in settings but it still thinks the mods are installed properly, and won't let me try to reinstall bbepis

Going to try a reinstall

**Comment by dmratcliffe** [comment] 2019-05-08 22:52
Reinstall (and clearing app data) fixed it, it appears the bug here is that the installer doesn't actually change the location.

**Comment by scottbot95** [comment] 2019-05-08 22:54
Cool just opened #68 to track that bug.

I'm curious, did you install RoR2 in the default location? I suspect it might have something to do with that. Also what version of the installer did you use?

**Comment by scottbot95** [comment] 2019-05-09 00:40
Since #68 has been a (ninja) problem since 0.3.1 (well before this issue was opened), and #68 was definitely causing a problem for this (and probably all mod installs in general), I'm going to assume it was the root cause and close this issue. 

If this turns out to still be a problem, I can re-open it.

**Closed by scottbot95** 2019-05-09 00:40 UTC
